In [9]:
import numpy as np
import pandas as pd

# Task 0
Read the dataset from csv file & perform data cleaning - remove all rows, which contains `?` in some columns.
Also check for data correctness (salary & salary $K).

In [11]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/adult.csv')
df = df.replace(to_replace=r'^\s*\?\s*$', value=np.nan, regex=True)
df = df.dropna()

if 'salary' in df.columns:
    df['salary'] = df['salary'].str.strip()

df.head()

,Unnamed: 0,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$
0,0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K,39
1,1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K,35
2,2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K,27
3,3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K,43
4,4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K,25

# Task 1
Print the count of men and women in the dataset.

In [12]:
df['sex'].value_counts()

sex
Male      20380
Female     9782
Name: count, dtype: int64

# Task 2
Find the average age of men in dataset

In [13]:
df[df['sex'] == 'Male']['age'].mean()

np.float64(39.18400392541707)

# Task 3
Get the percentage of people from Poland (native-country)

In [14]:
(df['native-country'] == 'Poland').mean() * 100

np.float64(0.18566408063125786)

# Task 4
Get the mean and standard deviation of the age for people who earn > 50K per year. After this, get it for those who earn <= 50K.

In [15]:
print(df[df['salary'] == '>50K']['age'].agg(['mean', 'std']))
print(df[df['salary'] == '<=50K']['age'].agg(['mean', 'std']))

mean    43.959110
std     10.269633
Name: age, dtype: float64
mean    36.608060
std     13.464631
Name: age, dtype: float64

# Task 5
Check, if there are some people without higher education (education: Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters, Doctorate), but with > 50K salary

In [16]:
higher_education = ['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate']
~df['education'].isin(higher_education) & (df['salary'] == '>50K')

0        False
1        False
2        False
3        False
4        False
         ...
32556    False
32557     True
32558    False
32559    False
32560     True
Length: 30162, dtype: bool

# Task 6
Get the statistics of age for each type of education. Use `groupby` and `describe` for this.

In [17]:
df.groupby('education')['age'].describe()

               count       mean        std   min   25%   50%   75%   max
education
10th           820.0  37.897561  16.225795  17.0  23.0  36.0  52.0  90.0
11th          1048.0  32.363550  15.089307  17.0  18.0  28.5  43.0  90.0
12th           377.0  32.013263  14.373710  17.0  19.0  28.0  41.0  79.0
1st-4th        151.0  44.622517  14.929051  19.0  33.0  44.0  56.0  81.0
5th-6th        288.0  41.649306  14.754622  17.0  28.0  41.0  53.0  82.0
7th-8th        557.0  47.631957  15.737479  17.0  34.0  49.0  60.0  90.0
9th            455.0  40.303297  15.335754  17.0  28.0  38.0  53.0  90.0
Assoc-acdm    1008.0  37.286706  10.509755  19.0  29.0  36.0  44.0  90.0
Assoc-voc     1307.0  38.246366  11.181253  19.0  30.0  37.0  45.0  84.0
Bachelors     5044.0  38.641554  11.577566  19.0  29.0  37.0  46.0  90.0
Doctorate      375.0  47.130667  11.471727  24.0  39.0  47.0  54.0  80.0
HS-grad       9840.0  38.640955  13.067730  17.0  28.0  37.0  48.0  90.0
Masters       1627.0  43.740012  10.735356  18.0  36.0  43.0  50.0  90.0
Preschool       45.0  41.288889  15.175672  19.0  30.0  40.0  53.0  75.0
Prof-school    542.0  44.249077  11.428098  25.0  36.0  43.0  50.0  90.0
Some-college  6678.0  36.135370  13.073528  17.0  25.0  35.0  45.0  90.0

# Task 7
Compare the married and non-married men salaries. Who earns more? (>50K or <=50K)
Married men are those, whom `marital-status` starts with "Married". Others are not.

In [18]:
men = df[df['sex'] == 'Male'].copy()
men['is_married'] = men['marital-status'].str.startswith('Married')
pd.crosstab(men['is_married'], men['salary'], normalize='index')

salary         <=50K      >50K
is_married
False       0.911506  0.088494
True        0.552016  0.447984

# Task 8
Get the max hours per week some person works. How many people works the same amount of hours per week?

In [19]:
max_hours = df['hours-per-week'].max()
num_people = (df['hours-per-week'] == max_hours).sum()
max_hours, num_people

(np.int64(99), np.int64(78))

# Task 9
Analyze the correlation between data in dataset. Understand connected fields in it and print highlight thier connection.

In [20]:
numeric_df = df.select_dtypes(include=['number']).drop(columns=['Unnamed: 0'], errors='ignore')
correlation_matrix = numeric_df.corr()
correlation_matrix

                     age  hours-per-week  salary K$
age             1.000000        0.101599   0.208203
hours-per-week  0.101599        1.000000   0.196378
salary K$       0.208203        0.196378   1.000000